### ISSUE TITLE
bug: Subnet delegation is not working

### ISSUE THREAD

**Issue by danieltothalteo** [Azure/terraform-azurerm-lz-vending#459]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.11.2
on windows_amd64
+ provider registry.terraform.io/azure/azapi v2.3.0
+ provider registry.terraform.io/azure/modtm v0.3.5
+ provider registry.terraform.io/hashicorp/azurerm v4.26.0
+ provider registry.terraform.io/hashicorp/random v3.7.1
+ provider registry.terraform.io/hashicorp/time v0.13.0
```

Please enter the module version that you are using:

```text
5.0.0
```

#### Steps to Reproduce

1. Using the module with `virtual_networks` provided with at least one subnet that has a subnet delegation
2. Running terraform plan or apply does not show or create any changes

#### Additional context

Pretty sure the issue is that in `variables.virtualnetwork.tf` under the variable `virtual_networks`, `subnets` is expecting the delegations in an optional list called `delegations`. The `virtual_networks` variable is passed to the inner `virtualnetwork` module as is, but in that modules `variables.tf` this parameter is called `delegation` and not `delegations`, thus making it null in every case.

**Comment by Remo-L5** [comment]
@danieltothalteo I see the issue, the subnet_v.delegation should have the 's' at the end.

**Comment by Arhughes14** [comment]
@matt-FFFFFF can you check this again please version 5.1.1 still seems to have a typo and delegations isn't working 

![Image](https://github.com/user-attachments/assets/b0f21ef8-93d5-4beb-8560-3f0337410d0e)

This is the difference

<img width="359" alt="Image" src="https://github.com/user-attachments/assets/83a135d0-71fa-487f-b7e0-31777e42820e" />

**Comment by Remo-L5** [comment]
@Arhughes14 in the locals file of the root module we map it over on line 84

https://github.com/Azure/terraform-azurerm-lz-vending/blob/main/locals.tf

**Comment by Arhughes14** [comment]
Ahh I see, any reason why the syntax hasn't been kept consistent with the AVM module?

**Comment by Remo-L5** [comment]
Technically this module is not yet an Azure Verified Module and moving to AVM seems likely in the future. Prior to v5’s release I did not notice the slight discrepancy and once we released it and I was working on this bug, I did not want to introduce the breaking Chang bee cause we follow semantic versioning and it should require a new version. I do agree with you that consistency is key going forward to make it easier to leverage our AVMs and accelerators.

**Comment by anaritavieira** [comment]
Hello @Remo-L5, 

The delegation is still not working on my side.
I've tried both `delegation` and `delegations`, but nothing happens—nothing is triggered to actually create the delegation. 

Below is how I'm defining it (in YAML format, which will be decoded):
    <img width="382" height="218" alt="Image" src="https://github.com/user-attachments/assets/73be54a9-4e5b-4a32-97d8-d5323b02d09c" />
The subnet (with the associated NSG) is created successfully.
